name: hw5-sac
dependencies:
    - python==3.4.5
    - pip:
        - gym==0.10.8
        - numpy==1.15.2
        - tensorflow==1.10.0
        - tensorflow-probability==0.4.0
        - mujoco-py==1.50.1.59
        - seaborn==0.9.0
